import os
import re

from pptx import Presentation
from pptx.util import Pt, Inches


# ============================================================
# CREATE PPT
# ============================================================

def create_ppt(data, followups, filename):

    # ========================================================
    # CREATE MEDIA DIRECTORY
    # ========================================================

    os.makedirs(
        "media",
        exist_ok=True
    )


    # ========================================================
    # FILE PATH
    # ========================================================

    path = os.path.join(
        "media",
        f"{filename}.pptx"
    )


    # ========================================================
    # CREATE PRESENTATION
    # ========================================================

    prs = Presentation()


    # ========================================================
    # WIDESCREEN 16:9
    # ========================================================

    # IMPORTANT:
    # Use Inches() instead of multiplication with 914400.
    # python-pptx requires integral EMU values.

    prs.slide_width = Inches(13.333)

    prs.slide_height = Inches(7.5)


    # ========================================================
    # CLEAN TEXT
    # ========================================================

    def clean_text(text):

        if not text:
            return ""

        text = str(text)

        text = text.replace(
            "\r\n",
            "\n"
        )

        text = text.replace(
            "\r",
            "\n"
        )

        return text.strip()


    # ========================================================
    # REMOVE MARKDOWN
    # ========================================================

    def remove_markdown(text):

        text = str(text)

        # Remove heading symbols
        text = re.sub(
            r"^#{1,6}\s*",
            "",
            text
        )

        # Remove bold
        text = text.replace(
            "**",
            ""
        )

        # Remove italic
        text = text.replace(
            "*",
            ""
        )

        # Remove inline code
        text = text.replace(
            "`",
            ""
        )

        return text.strip()


    # ========================================================
    # SPLIT CONTENT
    # ========================================================

    def split_content(text):

        text = clean_text(text)

        if not text:
            return []


        lines = text.split("\n")

        result = []


        for line in lines:

            line = line.strip()


            if not line:
                continue


            # ------------------------------------------------
            # REMOVE TABLE FORMAT
            # ------------------------------------------------

            if "|" in line:

                parts = [

                    part.strip()

                    for part in line.split("|")

                    if part.strip()

                ]


                # Ignore Markdown separator rows

                if parts and all(

                    re.fullmatch(
                        r"[-: ]+",
                        part
                    )

                    for part in parts

                ):

                    continue


                if parts:

                    line = " - ".join(parts)


            # ------------------------------------------------
            # REMOVE MARKDOWN
            # ------------------------------------------------

            line = remove_markdown(line)


            if line:

                result.append(line)


        return result


    # ========================================================
    # ADD TITLE SLIDE
    # ========================================================

    def add_title_slide():

        slide = prs.slides.add_slide(
            prs.slide_layouts[0]
        )


        # ----------------------------------------------------
        # TITLE
        # ----------------------------------------------------

        title = slide.shapes.title

        title.text = clean_text(
            data.topic
        )


        title_frame = title.text_frame


        for paragraph in title_frame.paragraphs:

            paragraph.font.size = Pt(34)

            paragraph.font.bold = True


        # ----------------------------------------------------
        # SUBTITLE
        # ----------------------------------------------------

        subtitle = slide.placeholders[1]


        subtitle.text = (
            "Educational Content Generated by EduGen AI"
        )


        for paragraph in subtitle.text_frame.paragraphs:

            paragraph.font.size = Pt(20)


        return slide


    # ========================================================
    # ADD NORMAL CONTENT SLIDE
    # ========================================================

    def add_content_slide(
        title,
        content_lines,
        font_size=18
    ):

        slide = prs.slides.add_slide(
            prs.slide_layouts[1]
        )


        # ----------------------------------------------------
        # SLIDE TITLE
        # ----------------------------------------------------

        slide_title = slide.shapes.title

        slide_title.text = clean_text(
            title
        )


        title_frame = slide_title.text_frame


        for paragraph in title_frame.paragraphs:

            paragraph.font.size = Pt(26)

            paragraph.font.bold = True


        # ----------------------------------------------------
        # CONTENT
        # ----------------------------------------------------

        text_frame = slide.placeholders[1].text_frame

        text_frame.clear()

        text_frame.word_wrap = True


        if not content_lines:

            content_lines = [
                "No information available."
            ]


        first = True


        for line in content_lines:

            line = line.strip()


            if not line:
                continue


            # ------------------------------------------------
            # GET PARAGRAPH
            # ------------------------------------------------

            if first:

                paragraph = text_frame.paragraphs[0]

                first = False

            else:

                paragraph = text_frame.add_paragraph()


            # ------------------------------------------------
            # FORMAT BULLET
            # ------------------------------------------------

            if line.startswith("- "):

                paragraph.text = (
                    "• "
                    + line[2:].strip()
                )

            elif line.startswith("•"):

                paragraph.text = line

            else:

                paragraph.text = line


            # ------------------------------------------------
            # FONT
            # ------------------------------------------------

            paragraph.font.size = Pt(
                font_size
            )

            paragraph.space_after = Pt(8)

            paragraph.level = 0


        return slide


    # ========================================================
    # ADD FOLLOW-UP SLIDE
    # ========================================================

    def add_followup_slide(
        question_number,
        question,
        answer
    ):

        slide = prs.slides.add_slide(
            prs.slide_layouts[1]
        )


        # ----------------------------------------------------
        # TITLE
        # ----------------------------------------------------

        title = slide.shapes.title


        title.text = (
            f"Follow-up Question {question_number}"
        )


        for paragraph in title.text_frame.paragraphs:

            paragraph.font.size = Pt(26)

            paragraph.font.bold = True


        # ----------------------------------------------------
        # CONTENT
        # ----------------------------------------------------

        text_frame = slide.placeholders[1].text_frame

        text_frame.clear()

        text_frame.word_wrap = True


        # ====================================================
        # QUESTION LABEL
        # ====================================================

        paragraph = text_frame.paragraphs[0]

        paragraph.text = "Student Question"

        paragraph.font.size = Pt(19)

        paragraph.font.bold = True

        paragraph.space_after = Pt(5)


        # ====================================================
        # QUESTION
        # ====================================================

        paragraph = text_frame.add_paragraph()

        paragraph.text = question

        paragraph.font.size = Pt(16)

        paragraph.space_after = Pt(12)


        # ====================================================
        # ANSWER LABEL
        # ====================================================

        paragraph = text_frame.add_paragraph()

        paragraph.text = "EduGen AI Answer"

        paragraph.font.size = Pt(19)

        paragraph.font.bold = True

        paragraph.space_after = Pt(5)


        # ====================================================
        # ANSWER
        # ====================================================

        answer_lines = split_content(
            answer
        )


        # Keep answer readable
        # Maximum 8 lines on one slide

        answer_lines = answer_lines[:8]


        for line in answer_lines:

            paragraph = text_frame.add_paragraph()

            paragraph.text = line

            paragraph.font.size = Pt(14)

            paragraph.space_after = Pt(4)


        return slide


    # ========================================================
    # SLIDE 1
    # ========================================================

    add_title_slide()


    # ========================================================
    # GET GENERATED CONTENT
    # ========================================================

    content = clean_text(
        data.content
    )


    lines = split_content(
        content
    )


    # ========================================================
    # DETECT SECTIONS
    # ========================================================

    sections = []

    current_title = None

    current_content = []


    for line in lines:

        original_line = line.strip()

        is_heading = False


        # ----------------------------------------------------
        # KNOWN SECTION HEADINGS
        # ----------------------------------------------------

        if re.match(

            r"^(Introduction|Definition|Basic Definition|"
            r"Important Concepts|How It Works|Example|"
            r"Applications|Advantages|Disadvantages|"
            r"Real[- ]World Example|Future Scope|Conclusion)"
            r"\s*:?",

            original_line,

            re.IGNORECASE

        ):

            is_heading = True


        # ----------------------------------------------------
        # NUMBERED SECTION HEADINGS
        # ----------------------------------------------------

        if re.match(

            r"^\d+\.\s+[A-Za-z]",

            original_line

        ):

            words = original_line.split()


            if len(words) <= 8:

                is_heading = True


        # ----------------------------------------------------
        # NEW SECTION
        # ----------------------------------------------------

        if is_heading:

            if current_title:

                sections.append(

                    (
                        current_title,
                        current_content
                    )

                )


            current_title = re.sub(

                r"^\d+\.\s*",

                "",

                original_line

            )


            current_title = current_title.rstrip(
                ":"
            )


            current_content = []


        else:

            if current_title:

                current_content.append(
                    original_line
                )

            else:

                current_title = "Introduction"

                current_content.append(
                    original_line
                )


    # ========================================================
    # ADD LAST SECTION
    # ========================================================

    if current_title:

        sections.append(

            (
                current_title,
                current_content
            )

        )


    # ========================================================
    # REMOVE EMPTY SECTIONS
    # ========================================================

    sections = [

        (
            title,
            section_content
        )

        for title, section_content
        in sections

        if section_content

    ]


    # ========================================================
    # MAXIMUM 12 SLIDES
    # ========================================================

    # Slide 1:
    # Title
    #
    # Slides 2-10:
    # Educational content
    #
    # Slides 11-12:
    # Follow-up questions
    #
    # Maximum = 12


    max_content_slides = 9

    max_followup_slides = 2


    # ========================================================
    # ADD EDUCATIONAL CONTENT
    # ========================================================

    content_sections = sections[
        :max_content_slides
    ]


    for title, section_content in content_sections:

        # Maximum 10 lines per slide
        section_content = section_content[:10]


        add_content_slide(

            title,

            section_content,

            font_size=18

        )


    # ========================================================
    # FILL EMPTY CONTENT SLIDES
    # ========================================================

    while len(prs.slides) < 10:

        add_content_slide(

            "Key Points",

            [

                "Important information from the "
                "generated educational content.",

                "Use the generated notes for detailed "
                "learning."

            ],

            font_size=18

        )


    # ========================================================
    # FOLLOW-UP QUESTIONS
    # ========================================================

    followup_count = 0


    for item in followups:

        if followup_count >= max_followup_slides:

            break


        question = clean_text(
            item.question
        )


        answer = clean_text(
            item.answer
        )


        if not question:

            continue


        if not answer:

            answer = "No answer available."


        followup_count += 1


        add_followup_slide(

            followup_count,

            question,

            answer

        )


    # ========================================================
    # NO FOLLOW-UP QUESTIONS
    # ========================================================

    if followup_count == 0:

        add_content_slide(

            "Student Learning",

            [

                "No follow-up questions were asked.",

                "Students can ask questions about "
                "the generated topic for further "
                "explanation."

            ],

            font_size=18

        )


        add_content_slide(

            "Conclusion",

            [

                "The educational content was generated "
                "using EduGen AI.",

                "Students can continue learning by "
                "asking follow-up questions."

            ],

            font_size=18

        )


    # ========================================================
    # FINAL SAFETY CHECK
    # ========================================================

    # Never allow more than 12 slides.

    while len(prs.slides) > 12:

        slide_id = prs.slides._sldIdLst[-1]

        prs.part.drop_rel(
            slide_id.rId
        )

        prs.slides._sldIdLst.remove(
            slide_id
        )


    # ========================================================
    # SAVE
    # ========================================================

    prs.save(path)


    return path